services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - account_service_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account_service_dev

volumes:
  account_service_data:
    name: account_service_data
    driver: local
    driver_opts:
      type: none
      device: ./.data
      o: bind
